In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [4]:
dataset=pd.read_csv("insurance_pre.csv")

In [5]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [10]:
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]

In [12]:
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(independent, dependent ,test_size=0.30,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [15]:
x_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

# Implementing Adaboost with  different Kernel and  parameter 

In [16]:
from sklearn.ensemble import AdaBoostRegressor
regressor=AdaBoostRegressor(random_state=0, n_estimators=50)
regressor.fit(x_train,y_train)

C:\Users\sindhiya maria\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


AdaBoostRegressor(random_state=0)

In [17]:
regressor.predict([[50,30.9,3,1,0]])

array([16708.77857483])

In [18]:
regressor.score(x_train,y_train)

0.8254486638430742

In [19]:
from sklearn.ensemble import AdaBoostRegressor
regressor=AdaBoostRegressor(random_state=0, n_estimators=500)
regressor.fit(x_train,y_train)

C:\Users\sindhiya maria\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


AdaBoostRegressor(n_estimators=500, random_state=0)

In [20]:
regressor.predict([[28,33,3,1,0]])

array([16708.77857483])

In [21]:
regressor.score(x_train,y_train)

0.8254486638430742

# Gridsearch Implementation for AdaBoost regressor

In [65]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor




param_grid={ 'n_estimators':[50,500,10,100,30,300,20,200],'random_state':[0]}
grid = GridSearchCV(AdaBoostRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 

# fitting the model for grid search 
grid.fit(x_train, y_train)                       

Fitting 5 folds for each of 8 candidates, totalling 40 fits


C:\Users\sindhiya maria\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GridSearchCV(estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'n_estimators': [50, 500, 10, 100, 30, 300, 20, 200],
                         'random_state': [0]},
             verbose=3)

In [66]:
re=grid.cv_results_
grid_predictions = grid.predict(x_test) 
   
# print classification report 
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)


print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'n_estimators': 10, 'random_state': 0}: 0.8618083410771146


In [67]:
table=pd.DataFrame.from_dict(re)

In [68]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.103984      0.019589         0.003388        0.000798   
1       0.232365      0.173365         0.003588        0.000488   
2       0.044787      0.011090         0.003588        0.001197   
3       0.054801      0.015335         0.003264        0.000388   
4       0.050501      0.014667         0.003290        0.000399   
5       0.097185      0.080971         0.003589        0.001197   
6       0.207579      0.209440         0.003389        0.000487   
7       0.242423      0.257434         0.003190        0.000399   

  param_n_estimators param_random_state  \
0                 50                  0   
1                500                  0   
2                 10                  0   
3                100                  0   
4                 30                  0   
5                300                  0   
6                 20                  0   
7                200                  0   

                                     params  split0_test_score  \
0   {'n_estimators': 50, 'random_state': 0}           0.774881   
1  {'n_estimators': 500, 'random_state': 0}           0.774881   
2   {'n_estimators': 10, 'random_state': 0}           0.816791   
3  {'n_estimators': 100, 'random_state': 0}           0.774881   
4   {'n_estimators': 30, 'random_state': 0}           0.774881   
5  {'n_estimators': 300, 'random_state': 0}           0.774881   
6   {'n_estimators': 20, 'random_state': 0}           0.774881   
7  {'n_estimators': 200, 'random_state': 0}           0.774881   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.796076           0.791655           0.816402           0.809327   
1           0.796076           0.791655           0.816402           0.809327   
2           0.796076           0.791655           0.816402           0.809327   
3           0.796076           0.791655           0.816402           0.809327   
4           0.796076           0.791655           0.816402           0.809327   
5           0.796076           0.791655           0.816402           0.809327   
6           0.796076           0.791655           0.816402           0.809327   
7           0.796076           0.791655           0.816402           0.809327   

   mean_test_score  std_test_score  rank_test_score  
0         0.797668        0.014456                2  
1         0.797668        0.014456                2  
2         0.806050        0.010392                1  
3         0.797668        0.014456                2  
4         0.797668        0.014456                2  
5         0.797668        0.014456                2  
6         0.797668        0.014456                2  
7         0.797668        0.014456                2

In [69]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:65
BMI:45
Children:1
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1


In [70]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[47865.29543781]
